// Custom cluster IDs
export const CLUSTERS = {
  BUTTON_OPTIONS: 0xA000,
  CODEINPUT_OPTIONS: 0xFCC1,
  WINCOVER_OPTIONS: 0xFCD1,
  LIGHT_MODE: 0xFCE2,
  RGB_LIGHT_MODE: 0xA001,
  MEDIA_PLAYER: 0xFCF1,
  RELAY_OPTIONS: 0xFCE1,
};

// Custom attribute IDs
export const ATTR = {
  // Button cluster
  BUTTON_FEEDBACK: 0xA000,
  BUTTON_LONG_PRESS_DELAY: 0xA001,
  BUTTON_FEEDBACK_COLOR: 0xA002,
  BUTTON_FEEDBACK_LEVEL: 0xA003,

  // Code input cluster
  CODEINPUT_CODE: 0xFCC0,
  CODEINPUT_TIMEOUT: 0xFCC1,
  CODEINPUT_LOCKOUT: 0xFCC2,
  CODEINPUT_LOCKOUT_PROGRESSIVE: 0xFCC3,

  // Window covering / gate
  WINCOVER_TUYA_MOVING_STATE: 0xF000,
  WINCOVER_TUYA_CALIBRATION: 0xF001,
  WINCOVER_TUYA_MOTOR_REVERSAL: 0xF002,
  WINCOVER_MOES_CALIBRATION_TIME: 0xF003,
  WINCOVER_WARN_ON_MOVE: 0xFCD0,

  // Light clusters
  LIGHT_MODE: 0xFCE3,
  LIGHT_INTERVAL: 0xFCE4,
  RGB_LIGHT_MODE: 0xA002,
  RGB_LIGHT_INTERVAL: 0xA003,

  // Media player
  MEDIA_PLAYER_STATE: 0xFCF2,
  MEDIA_PLAYER_COMMAND: 0xFCF3,
  MEDIA_PLAYER_VOLUME: 0xFCF4,
  MEDIA_PLAYER_TRACK_COUNT: 0xFCF5,
  MEDIA_PLAYER_CURRENT_TRACK_NUM: 0xFCF6,
  MEDIA_PLAYER_PLAYMODE: 0xFCF7,

  // Relay cluster
  RELAY_TYPE: 0xFCE2,
  RELAY_COUNTDOWN: 0xFCE3,
};
